@idenitywebapiauthenitcation_HostAddress = https://localhost:7239

GET {{idenitywebapiauthenitcation_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{idenitywebapiauthenitcation_HostAddress}}/api/user
Authorization: Bearer CfDJ8BHWDgVmgGlCt9OD0TT-MJ1oYon2Tv_C51fBLmryZSs4AW9pgQc7u2dYl-VcNyTsXhtMD_IaoVac9wHH35rVqJEKL7ZhoB4Ibdqj3h3Vzc_Ruwky52z3tU2q-J_o2Hl827gVN-RdhLJdWvVRgjySGBT81CgtfxkOumVuQqdwxkLswhfHUbYEcD_HGx1PUe1qcG1yaGBraP4qlLNWeLQkA4MrMERWhgpmPbqZXCArhllqySMNGmG8xGZ21i-kyuHl28sZgNtK_SrFZu59tF_NIZ3LeF8TxU-klkygslXmUg6sNCtwQ4TOXF6fPYk8BgNP2uTMymWgBYaGCELHPzskkueXXNDXINA1I6EIG9T35Jh3UAjckyF_Xf3Y85hR9RAlxBPJmkUisM9ag4HKADfgC-qP9tdIffQoP9QwidWLZhsRcp48DvbozVPcpLhJedwY5YbhuRl45zEYhMkJVxE6moZv75OOHypNakUgjU8tSZFV8Zy4_3lGBrf_ii4082gxxjIC_er0W9ktRfL2BCxnDMEjmurN_Rb86cKbLQ-BYyfEhAtbr6RZXYoHL-01yyZzVZRWIWrJJep9KTSTmKQNiAuWfrbd-L-DvpGA7cWtpnlRXltXXHE0PKlMWd7bTYHLakjniGG2mSCR9WP4wQ8gP6ohmVVu88FzYM_vRprQdLuCDiIoyo700V2bQA1UEDMc9A
###
